part3:part2
	gcc base_operation.c disk_manager.c file_system.c fileSystemOper.c -lm  -w -o fileSystemOper
	
part2:
	gcc base_operation.c disk_manager.c file_system.c makeFileSystem.c -lm  -w -o makeFileSystem
